- hosts: app:nginx
  become: yes
  roles:
    - geerlingguy.docker
  tags: 
  - docker

- hosts: app
  become: yes
  tasks:
  - name: Create a webapp container
    community.docker.docker_container:
      name: webapp
      image: vscoder/webdebugger
      ports:
      - 8080:8080

- hosts: nginx
  become: yes
  tasks:
  - name: Create nginx config folder 
    ansible.builtin.file:
      path: /etc/nginx
      state: directory
  
  - name: Create nginx logs folder 
    ansible.builtin.file:
      path: /var/log/nginx
      state: directory

  - name: Copy config
    ansible.builtin.copy:
      content: "{{ nginx_config }}"
      dest: /etc/nginx/nginx.conf

  - name: Create a nginx container
    community.docker.docker_container:
      name: nginx
      image: nginx
      recreate: yes
      ports:
      - 80:80
      volumes:
        - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /etc/hosts:/etc/hosts
        - /var/log/nginx:/var/log/nginx

  vars:
  - nginx_config: |
      user www-data;
      worker_processes auto;
      pid /run/nginx.pid;
      include /etc/nginx/modules-enabled/*.conf;

      events {
        worker_connections  1024;
      }

      http {
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        upstream backend {
          server app-0:8080;
        }
        server {
            listen 80;
            location / {
                proxy_pass http://backend;
            }
        }
      }
