---
# tasks file for filebeat
- name: Download filebeat
  ansible.builtin.get_url:
    url: "{{ filebeat_url }}"
    dest: /tmp

- name: Install filebeat
  ansible.builtin.apt:
    deb: /tmp/filebeat-{{ filebeat_version }}-amd64.deb
    state: present

- name: Replace filebeat config
  ansible.builtin.copy:
    content: "{{ filebeat_config }}"
    dest: /etc/filebeat/filebeat.yml
  notify: Restart filebeat
  