---
# tasks file for nginx
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: yes

- name: Replace config
  ansible.builtin.template:
    src: "{{ nginx_config_path }}"
    dest: /etc/nginx/nginx.conf