- hosts: prometheus
  become: true
  tags: docker
  pre_tasks:
    - name: Apt update
      ansible.builtin.apt:
        update_cache: yes
  roles:
    - geerlingguy.docker
    
    
- hosts: prometheus
  become: true
  tags: prometheus
  roles:
    - ../roles/prometheus

- hosts: all
  become: true
  tags: prometheus
  roles:
    - ../roles/node-exporter


