- hosts: loadbalanser
  remote_user: vagrant
  become: true
  tags: loadbalanser
  roles:
    - role: 'roles/nginx'
    - role: 'roles/keepalived'
  vars:
  # nginx vars
    webservers:
    - 192.168.0.21
    - 192.168.0.22
    nginx_config_path: "templates/nginx.yaml.j2"
    # keepalived vars
    virtual_ipaddress: 192.168.0.50
    master_host: 192.168.0.11 # all another will be backup
    keepalived_config_path: "templates/keepalived.conf.j2"


- hosts: webserver
  remote_user: vagrant
  become: true
  tags: webserver
  roles:
    - geerlingguy.docker

- hosts: webserver    
  remote_user: vagrant
  become: true
  tags: webapp
  roles:
    - 'roles/webapp'