- hosts: rabbit
  become: true
  roles:
    - role: 'roles/rabbitmq-docker'
      vars:
        erlang_cookie: SRENBEZHALWYXNCYTJNG
        rabbitmq_master: rabbit-0
        rabbitmq_slaves:
        - rabbit-1
        - rabbit-2
