- hosts: iscsi
  become: true
  tags: 
    - install
    - target
  roles:
    - role: 'roles/iscsi'

- hosts: initiator
  become: true
  tags: 
    - install
    - initiator
  roles:
    - role: 'roles/iscsi'    